[package]
name = "steam-api-rs"
version = "0.1.0"
authors = ["Aleksey Grachev <alg37@yandex-team.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = "0.1"
chrono = "0.4"